
program := "main"

_default:
    @echo $(ghc --version)
    @echo
    @just --list

dev:
    entr sh -c 'clear && just build && ./build/{{program}}' <<< {{program}}.hs

build:
    ghc {{program}}.hs -outputdir build -o build/{{program}}
