
program := "Main"

_default:
    @echo $(ghc --version)
    @echo
    @just --list

dev:
    entr sh -c 'clear && just build && ./out/{{program}}' <<< src/{{program}}.hs

build:
    ghc --make src/{{program}}.hs -outputdir out -o out/{{program}} -i:lib
